server:
  port: 5555

spring:
  activemq:
    broker-url: tcp://192.168.71.131:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true      # false = queue    true =  topic


mytopic: boot-activemq-topic

